spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/benchmark_db6
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
  data:
    rest:
      base-path: /

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
server:
  port: 8081
